<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Recipe;
use Illuminate\Support\Facades\DB;

class RecipeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('recipes')->delete();

        $recipes = [
            [
                'title' => 'Avocado Toast',
                'description' => 'Simple and delicious avocado toast with cherry tomatoes',
                'instructions' => 'Toast bread, mash avocado, add toppings',
                'prep_time' => 5,
                'cook_time' => 5,
                'total_time' => 10,
                'servings' => 1,
                'difficulty' => 'easy',
                'meal_type' => 'breakfast',
                'image_path' => 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Greek Salad',
                'description' => 'Fresh Mediterranean salad with feta cheese and olives',
                'instructions' => 'Chop vegetables, add feta, dress with olive oil',
                'prep_time' => 10,
                'cook_time' => 0,
                'total_time' => 10,
                'servings' => 2,
                'difficulty' => 'easy',
                'meal_type' => 'lunch',
                'image_path' => 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Grilled Chicken Breast',
                'description' => 'Tender grilled chicken with herbs and spices',
                'instructions' => 'Season chicken, grill for 6-8 minutes per side',
                'prep_time' => 10,
                'cook_time' => 15,
                'total_time' => 25,
                'servings' => 4,
                'difficulty' => 'medium',
                'meal_type' => 'dinner',
                'image_path' => 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Veggie Stir Fry',
                'description' => 'Quick and healthy vegetable stir fry with soy sauce',
                'instructions' => 'Chop vegetables, stir fry in hot wok with sauce',
                'prep_time' => 15,
                'cook_time' => 10,
                'total_time' => 25,
                'servings' => 2,
                'difficulty' => 'easy',
                'meal_type' => 'dinner',
                'image_path' => 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Overnight Oats',
                'description' => 'No-cook breakfast with oats, milk, and fresh berries',
                'instructions' => 'Mix oats with milk, refrigerate overnight, add toppings',
                'prep_time' => 5,
                'cook_time' => 0,
                'total_time' => 5,
                'servings' => 1,
                'difficulty' => 'easy',
                'meal_type' => 'breakfast',
                'image_path' => 'https://images.unsplash.com/photo-1517673132405-a56a62b18caf?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Pasta Primavera',
                'description' => 'Light pasta with seasonal vegetables and garlic',
                'instructions' => 'Cook pasta, sauté vegetables, toss together',
                'prep_time' => 15,
                'cook_time' => 20,
                'total_time' => 35,
                'servings' => 4,
                'difficulty' => 'medium',
                'meal_type' => 'dinner',
                'image_path' => 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Chocolate Chip Cookies',
                'description' => 'Classic homemade chocolate chip cookies',
                'instructions' => 'Mix ingredients, scoop dough, bake at 350°F for 12 minutes',
                'prep_time' => 15,
                'cook_time' => 12,
                'total_time' => 27,
                'servings' => 24,
                'difficulty' => 'easy',
                'meal_type' => 'snack',
                'image_path' => 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Quinoa Buddha Bowl',
                'description' => 'Nutritious bowl with quinoa, roasted veggies, and tahini',
                'instructions' => 'Cook quinoa, roast vegetables, assemble bowl with dressing',
                'prep_time' => 10,
                'cook_time' => 30,
                'total_time' => 40,
                'servings' => 2,
                'difficulty' => 'medium',
                'meal_type' => 'lunch',
                'image_path' => 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Salmon Teriyaki',
                'description' => 'Glazed salmon with homemade teriyaki sauce',
                'instructions' => 'Prepare sauce, brush on salmon, bake at 400°F for 15 minutes',
                'prep_time' => 10,
                'cook_time' => 15,
                'total_time' => 25,
                'servings' => 2,
                'difficulty' => 'medium',
                'meal_type' => 'dinner',
                'image_path' => 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Smoothie Bowl',
                'description' => 'Thick smoothie topped with fresh fruits and granola',
                'instructions' => 'Blend frozen fruits with liquid, pour into bowl, add toppings',
                'prep_time' => 5,
                'cook_time' => 0,
                'total_time' => 5,
                'servings' => 1,
                'difficulty' => 'easy',
                'meal_type' => 'breakfast',
                'image_path' => 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Margherita Pizza',
                'description' => 'Classic Italian pizza with fresh mozzarella and basil',
                'instructions' => 'Prepare dough, add sauce and toppings, bake at 450°F for 12-15 minutes',
                'prep_time' => 20,
                'cook_time' => 15,
                'total_time' => 35,
                'servings' => 4,
                'difficulty' => 'medium',
                'meal_type' => 'dinner',
                'image_path' => 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Caesar Salad',
                'description' => 'Crisp romaine lettuce with creamy Caesar dressing and croutons',
                'instructions' => 'Chop romaine, prepare dressing, add parmesan and croutons',
                'prep_time' => 10,
                'cook_time' => 0,
                'total_time' => 10,
                'servings' => 2,
                'difficulty' => 'easy',
                'meal_type' => 'lunch',
                'image_path' => 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Beef Tacos',
                'description' => 'Seasoned ground beef in soft tortillas with fresh toppings',
                'instructions' => 'Brown beef with spices, warm tortillas, assemble with toppings',
                'prep_time' => 10,
                'cook_time' => 15,
                'total_time' => 25,
                'servings' => 4,
                'difficulty' => 'easy',
                'meal_type' => 'dinner',
                'image_path' => 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Banana Pancakes',
                'description' => 'Fluffy pancakes with mashed banana and maple syrup',
                'instructions' => 'Mix batter with mashed banana, cook on griddle, serve with syrup',
                'prep_time' => 10,
                'cook_time' => 15,
                'total_time' => 25,
                'servings' => 2,
                'difficulty' => 'easy',
                'meal_type' => 'breakfast',
                'image_path' => 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400',
                'is_active' => true,
            ],
            [
                'title' => 'Thai Curry',
                'description' => 'Creamy coconut curry with vegetables and aromatic spices',
                'instructions' => 'Sauté curry paste, add coconut milk and vegetables, simmer',
                'prep_time' => 15,
                'cook_time' => 20,
                'total_time' => 35,
                'servings' => 4,
                'difficulty' => 'medium',
                'meal_type' => 'dinner',
                'image_path' => 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400',
                'is_active' => true,
            ],
        ];

        foreach ($recipes as $recipe) {
            Recipe::create($recipe);
        }
    }
}
